name: Bloodmoon
version: 1.2.3
main: com.rappelr.bloodmoon.Bloodmoon
authors: [Rappelr]
api-version: 1.14
softdepend: [ItemsAdder]
load: POSTWORLD
description: A Bloodmoon plugin for Alterria
commands:
  bloodmoon:
    description: Core command, try /bm help
    usage: /bloodmoon help
    aliases: [bm]
permissions:
  bloodmoon.checkdays:
    description: Allows a user to check the amount of days until the next bloodmoon
    default: true
  bloodmoon.last:
    description: Allows a user to check the amount of days since the last bloodmoon
    default: true
  bloodmoon.list:
    description: Allows a user to check all worlds for bloodmoons
    default: op
  bloodmoon.admin:
    description: Allows a user to use all administrative subcommands
    default: op