name: Bloodmoon
version: 1.1.1
main: com.rappelr.bloodmoon.Bloodmoon
authors: [Rappelr]
api-version: 1.14
depend: []
description: A Bloodmoon overhaul for BobSMP
commands:
  bloodmoon:
    description: Bloodmoon core command, subcommands use different permissions
    usage: /<bloodmoon>
permissions:
  bloodmoon.checkdays:
    description: Allows a user to check the amount of days until the next bloodmoon
    default: true
  bloodmoon.last:
    description: Allows a user to check the amount of days since the last bloodmoon
    default: true
  bloodmoon.list:
    description: Allows a user to check all worlds for bloodmoons
    default: op
  bloodmoon.admin:
    description: Allows a user to use all administrative subcommands
    default: op